name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: sudo apt-get install libsqlite3-dev cmake liblog4cpp5-dev libboost-all-dev libevent-dev libprotobuf-dev libgoogle-glog-dev libgflags-dev libhiredis-dev libgtest-dev libsnappy-dev
    - name: thrift
      run: |
        sudo apt-get install automake bison flex g++ git libboost-all-dev libevent-dev libssl-dev libtool make pkg-config
        git clone https://github.com/apache/thrift.git
        cd thrift
        sh bootstrap.sh
        ./configure --without-qt5 --without-as3 --without-c_glib --without-csharp --without-java --without-erlang --without-nodejs --without-nodets --without-lua  --without-python --without-py3 --without-perl --without-php --without-php_extension --without-dart --without-ruby --without-haskell --without-go --without-swift --without-rs --without-cl --without-haxe --without-dotnetcore --without-d
        make -j
        sudo make install
    - name: cmake
      run: cmake .
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
