name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: sudo apt-get update; sudo apt-get install cmake libboost-all-dev libevent-dev libprotobuf-dev libgoogle-glog-dev libgflags-dev libhiredis-dev libgtest-dev
    - name: cmake
      run: cmake .
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
