name: docker build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: use docker build
      uses: phantom9999/actions@v18
      with:
          shell_main: "action.sh"
          shell_post: "action_post.sh"
